### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by arriflex** [theminor/node-red-contrib-tcc-honeywell#1]
I'm having issues with this. It works only once in a blue moon (although it's magical when it does!) and not predictably. Some of the time there is no response and often it crashes Node-Red.

Crash log:
Nov 25 23:19:24 hassbian Node-RED[7651]: 25 Nov 23:19:24 - [red] Uncaught Exception:
Nov 25 23:19:24 hassbian Node-RED[7651]: 25 Nov 23:19:24 - TypeError: callback is not a function
Nov 25 23:19:24 hassbian Node-RED[7651]:     at /home/pi/.node-red/node_modules/node-red-contrib-tcc-honeywell/node-tcc-honeywell.js:40:5
Nov 25 23:19:24 hassbian Node-RED[7651]:     at Request._callback (/home/pi/.node-red/node_modules/node-red-contrib-tcc-honeywell/node-tcc-honeywell.js:31:4)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at Request.self.callback (/home/pi/.node-red/node_modules/request/request.js:185:22)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at emitTwo (events.js:126:13)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at Request.emit (events.js:214:7)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at Request.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1161:10)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at emitOne (events.js:116:13)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at Request.emit (events.js:211:7)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/request/request.js:1083:12)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at Object.onceWrapper (events.js:313:30)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at emitNone (events.js:111:20)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at IncomingMessage.emit (events.js:208:7)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at endReadableNT (_stream_readable.js:1064:12)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Nov 25 23:19:24 hassbian Node-RED[7651]:     at process._tickCallback (internal/process/next_tick.js:180:9)

Version info:
Nov 25 23:29:04 hassbian Node-RED[7959]: 25 Nov 23:29:04 - [info] Node-RED version: v0.19.1
Nov 25 23:29:04 hassbian Node-RED[7959]: 25 Nov 23:29:04 - [info] Node.js  version: v8.11.4
Nov 25 23:29:04 hassbian Node-RED[7959]: 25 Nov 23:29:04 - [info] Linux 4.14.52+ arm LE

**Comment by theminor** [comment]
Update and see if this issue is fixed in https://github.com/theminor/node-red-contrib-tcc-honeywell/commit/9d7ca7d4b6049d184080425115937916d4292142

**Comment by arriflex** [comment]
Seems to have fixed the crashing from the TypeError.
